import { POSITIONS } from "..";

const DEFAULT_TOAST_DISPLAY_TIME = 3000; //ms
const DEFAULT_TOAST_POSITION = POSITIONS.RIGHT;
const TOAST_LIMIT = 10;

export { DEFAULT_TOAST_DISPLAY_TIME, DEFAULT_TOAST_POSITION, TOAST_LIMIT };
