import { POSITIONS, VARIANTS } from "..";

export const DEFAULT_TOAST_DISPLAY_TIME = 3000; //ms
export const DEFAULT_TOAST_POSITION = POSITIONS.RIGHT;
export const DEFAULT_VARIANT = VARIANTS.INFO;
export const TOAST_LIMIT = 10;
